//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Account_Login
{
    protected global::System.Web.UI.WebControls.Literal FailureText;
    protected global::System.Web.UI.WebControls.TextBox UserName;
    protected global::System.Web.UI.WebControls.TextBox Password;
    protected global::System.Web.UI.WebControls.CheckBox RememberMe;
    protected global::Telerik.Web.UI.RadButton btnLogin;
    protected global::System.Web.UI.WebControls.HyperLink RegisterHyperLink;
}